services:
  - type: web
    name: numbott-telethon
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: false
    healthCheckPath: /health
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: LOG_CHANNEL_ID
        sync: false
      - key: CHECK_CHANNELS
        sync: false
      - key: JOIN_URLS
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        value: numbott
      - key: PUBLIC_BASE_URL
        sync: false
      - key: SMM_SERVER_1_KEY
        sync: false
      - key: SMM_SERVER_2_KEY
        sync: false
